<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            ['name' => 'HTML'],
            ['name' => 'CSS'],
            ['name' => 'JavaScript'],
            ['name' => 'PHP'],
            ['name' => 'Laravel'],
            ['name' => 'Vue.js'],
            ['name' => 'React'],
            ['name' => 'Angular'],
            ['name' => 'Node.js'],
            ['name' => 'Python'],
            ['name' => 'Java'],
            ['name' => 'SQL'],
            ['name' => 'MySQL'],
            ['name' => 'Git'],
            ['name' => 'Docker'],
            ['name' => 'AWS'],
            ['name' => 'Azure'],
            ['name' => 'Linux'],
            ['name' => 'Aprendizado de Máquina'],
            ['name' => 'Segurança Cibernética'],
            ['name' => 'Blockchain'],
            ['name' => 'DevOps'],
            ['name' => 'Design de UI/UX'],
            ['name' => 'Desenvolvimento Móvel'],
            ['name' => 'Desenvolvimento Web'],
            ['name' => 'Teste de Software'],
            ['name' => 'Desenvolvimento Android'],
            ['name' => 'Desenvolvimento iOS'],
            ['name' => 'Flutter'],
            ['name' => 'Swift'],
            ['name' => 'Kotlin'],
            ['name' => 'React Native'],
            ['name' => 'Firebase'],
            ['name' => 'MongoDB'],
            ['name' => 'SQLite'],
            ['name' => 'API REST'],
            ['name' => 'GraphQL'],
            ['name' => 'AWS Lambda'],
            ['name' => 'Google Cloud Platform'],
            ['name' => 'Microsoft Azure'],
            ['name' => 'GitHub'],
            ['name' => 'GitLab'],
            ['name' => 'Bitbucket'],
            ['name' => 'Kubernetes'],
            ['name' => 'Jenkins'],
            ['name' => 'CI/CD'],
            ['name' => 'Testes Automatizados'],
            ['name' => 'Testes Unitários'],
            ['name' => 'Testes de Integração'],
            ['name' => 'Selenium'],
            ['name' => 'Cypress'],
            ['name' => 'Gestão de Projetos'],
            ['name' => 'Metodologia Ágil'],
            ['name' => 'Scrum'],
            ['name' => 'Kanban'],
            ['name' => 'Cloud Computing'],
            ['name' => 'Microservices'],
            ['name' => 'Arquitetura de Software'],
            ['name' => 'Padrões de Projeto'],
            ['name' => 'C'],
            ['name' => 'C++'],
            ['name' => 'C#'],
            ['name' => 'Go'],
            ['name' => 'Rust'],
            ['name' => 'Perl'],
            ['name' => 'Ruby'],
            ['name' => 'Scala'],
            ['name' => 'Elixir'],
            ['name' => 'Haskell'],
            ['name' => 'R'],
            ['name' => 'MATLAB'],
            ['name' => 'Dart'],
            ['name' => 'TypeScript'],
            ['name' => 'Objective-C'],
            ['name' => 'Assembly'],
            ['name' => 'COBOL'],
            ['name' => 'Fortran'],
            ['name' => 'Pascal'],
            ['name' => 'Groovy'],
            ['name' => 'Erlang'],
            ['name' => 'Lisp'],
            ['name' => 'F#'],
            ['name' => 'Scheme'],
            ['name' => 'VHDL'],
            ['name' => 'Verilog'],
            ['name' => 'Prolog'],
            ['name' => 'Ada'],
            ['name' => 'ABAP'],
            ['name' => 'Solidity'],
            ['name' => 'Tcl'],
            ['name' => 'SAS'],
            ['name' => 'Bootstrap'],
            ['name' => 'Tailwind CSS'],
            ['name' => 'Foundation'],
            ['name' => 'Bulma'],
            ['name' => 'Semantic UI'],
            ['name' => 'Materialize'],
            ['name' => 'Sass'],
            ['name' => 'LESS'],
            ['name' => 'Stylus'],
            ['name' => 'jQuery'],
            ['name' => 'Ember.js'],
            ['name' => 'Backbone.js'],
            ['name' => 'Svelte'],
            ['name' => 'Meteor'],
            ['name' => 'Aurelia'],
            ['name' => 'Alpine.js'],
            ['name' => 'Nuxt.js'],
            ['name' => 'Next.js'],
            ['name' => 'Gatsby.js'],
            ['name' => 'Express.js'],
            ['name' => 'NestJS'],
            ['name' => 'Redux'],
            ['name' => 'MobX'],
            ['name' => 'RxJS'],
            ['name' => 'Three.js'],
            ['name' => 'D3.js'],
            ['name' => 'Chart.js'],
            ['name' => 'Jest'],
            ['name' => 'Mocha'],
            ['name' => 'Chai'],
            ['name' => 'Sinon'],
            ['name' => 'Enzyme'],
        ];

        foreach ($skills as $s) {
            Skill::create([
                'name' => $s['name'],
            ]);
        }
    }
}
